gatling/gatling-enterprise-control-plane-deployment

terraform/aws/control-plane/main.tf
terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/modules/ecs/variables.tf
terraform/aws/control-plane/modules/s3/main.tf
terraform/aws/control-plane/modules/s3/variables.tf
terraform/aws/control-plane/variables.tf

**Motivation:**
`command` allow custom command for the control plane image. `extra_content` alllow extra properties in `control-plane.conf`

feat: add command and extra_content to control plane

---

terraform/aws/control-plane/main.tf
terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/modules/ecs/variables.tf
terraform/aws/control-plane/modules/iam/main.tf
terraform/aws/control-plane/modules/iam/outputs.tf
terraform/aws/control-plane/modules/iam/variables.tf
terraform/aws/control-plane/modules/s3/main.tf
terraform/aws/control-plane/modules/s3/variables.tf
terraform/aws/control-plane/outputs.tf
terraform/aws/control-plane/variables.tf
terraform/aws/location/main.tf
terraform/aws/location/variables.tf
terraform/examples/AWS-private-location/main.tf
terraform/examples/AWS-private-package/main.tf

I'm adding support for optionally pushing Control Plane service logs to CloudWatch to help with deployment and debugging, as it's a recurring request from multiple prospects.
Changes Made:
- Added optional CloudWatch policy for Control Plane service role.
- Added optional logConfiguration to  Control Plane task definition.
- Refactoring
I believe I should add a section to our AWS Private Locations documentation detailing the necessary CloudWatch permissions and the changes needed in the service task definition. What do you think?

feat: AWS Terraform CloudWatch Logs

---

helm-chart/Chart.yaml
helm-chart/templates/deployment.yaml
helm-chart/values.yaml

Motivation:
- Set load generators as burstable by default. This allows resources to scale dynamically based on load tests. Throttling or evicting these jobs when fully saturated makes sense, as the load test can simply be restarted if necessary.
- Set control plane to guaranteed QoS class by default, as its role as the orchestrator of load generators makes evictions unacceptable.
https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#quality-of-service-classes
Modifications:
- Set same control plane resource requests and resource limits in order to ensure guaranteed QoS class.
- Set different load generator resource requests and resource limits in order to ensure burstable QoS class.

[Helm] Set QoS policies for CP and PL

---

terraform/azure/control-plane/main.tf
terraform/azure/control-plane/modules/container-app/main.tf
terraform/azure/control-plane/modules/container-app/variables.tf
terraform/azure/control-plane/modules/role-assignment/main.tf
terraform/azure/control-plane/modules/role-assignment/variables.tf
terraform/azure/control-plane/modules/storage-account/main.tf
terraform/azure/control-plane/modules/storage-account/variables.tf
terraform/azure/control-plane/variables.tf
terraform/azure/location/main.tf
terraform/azure/location/variables.tf
terraform/azure/private-package/main.tf
terraform/azure/private-package/variables.tf
terraform/examples/AZURE-private-location/README.md
terraform/examples/AZURE-private-location/main.tf
terraform/examples/AZURE-private-package/README.md
terraform/examples/AZURE-private-package/main.tf

Motivation:
This PR enhances enterprise cloud support by introducing forward proxy configuration for control plane & locations, improving security with Azure Key Vault integration, and adding support for private package server configurations. It also focuses on maintainability by replacing deprecated storage_account_name from azurerm_storage_share.
Modifications:
- Add enterprise cloud variables for forward proxy support on control plane & locations.
- Handle CP token secret through Azure Key Vault.
- Update private package configuration.
- Replace deprecated storage_account_name from azurerm_storage_share with storage_account_id.
- Replace gatling_storage_share.id argument in azurerm_storage_share_file with gatling_storage_share.url.

[Terraform-Azure] v2 - Reference secret through Key Vault

---

terraform/aws/control-plane/main.tf
terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/modules/ecs/variables.tf
terraform/aws/control-plane/variables.tf
terraform/aws/location/main.tf
terraform/aws/location/variables.tf
terraform/examples/AWS-private-location/README.md
terraform/examples/AWS-private-location/main.tf
terraform/examples/AWS-private-package/README.md
terraform/examples/AWS-private-package/main.tf

Motivation:
Support new location conf option : auto_associate_public_ipv4 and improve location & control plane customization.
Modifications:
- Add location auto_associate_public_ipv4 var.
- Add missing ami_id to support custom AMIs and sys props var on location.
- Add customizable ECS task definition control plane container cpu and memory in order to support vertical scalability.

[Terraform - AWS] chore:  Add location auto_associate_public_ipv4, ami_id, sys props & CP ecs task cpu & mem vars

---

helm-chart/Chart.yaml
helm-chart/README.md
helm-chart/templates/_config.tpl
helm-chart/values.yaml

Motivation:
Securely storing control plane token as Kubernetes secret.
Modifications:
- Changed configuration in order to reference control plane token as environment variable.
- Add sample snippet mounting secret as environment variable on the control plane container.

Feat: Add Helm Chart config reference token from an environment variable

---

helm-chart/Chart.yaml
helm-chart/templates/_config.tpl
helm-chart/templates/deployment.yaml
helm-chart/templates/serviceaccount.yaml
helm-chart/values.yaml

Motivation:
Access cloud specific resources from control plane/load generators in order to securely access storage service or spawn cloud load generators.
Modifications:
- Updated values.yaml to support optional IAM Role ARN/AzureClientID/GCPServiceAccount on the control plane.
- Added conditional K8s Service Account annotations.
- Added conditional `azure.workload.identity/use: "true"` to deployment template.

Feat: Helm support for linking SA with Cloud specific permissions

---

helm-chart/values.yaml

Motivation:
Direct end-users to Gatling doc for configuring private locations and setting up proxies that change dynamically.
Modifications:
- Remove enterpriseCloud block and replace it with Gatling doc for proxies.
- Add location configuration doc links as reference.
- Add missing image `id` for GCP location.
- Add `serviceAccountName`, `imagepullSecrets`, `volumeMounts`, `volumes` to K8s location to ease configuration for end-users.

Feat: Replace enterpriseCloud block with URL referencing Gatling doc

---

terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/modules/iam/main.tf

Motivation:
Fix incorrect conditions for `private-package` on ECS module.
Modification:
- Replace `private-package` map check with map length.

Fix: private-package condition on Private Locations

---

terraform/aws/control-plane/modules/iam/main.tf

Motivation:
Fix issue with Elastic IP policies: `MalformedPolicyDocument: Statement IDs (SID) must be alpha-numeric`.
Modification:
- Sanitize `AllowElasticIP_${data.aws_eip.by_ip[elastic_ip].id}"` to `"AllowElasticIP${replace(data.aws_eip.by_ip[elastic_ip].id, "-", "")}"`

fix: sanitize IAM elasticIP policy Sid

---

terraform/aws/control-plane/modules/iam/main.tf

Motivation:
Fix permission to ec2:AssociateAddress on EIP resources.
Modification:
Replace `address` with `elastic-ip` on EIP resource ARN.

Fix: replace address with elastic-ip on EIP resource ARN

---

terraform/azure/control-plane/modules/container-app/main.tf
terraform/azure/control-plane/modules/container-app/variables.tf
terraform/azure/control-plane/modules/role-assignment/main.tf
terraform/azure/control-plane/modules/storage-account/main.tf
terraform/azure/control-plane/variables.tf
terraform/azure/location/variables.tf
terraform/azure/private-package/variables.tf
terraform/examples/AZURE-private-location/README.md
terraform/examples/AZURE-private-location/main.tf
terraform/examples/AZURE-private-package/README.md
terraform/examples/AZURE-private-package/main.tf

Motivation:
Add granular defaults to input arg objects in order to improve the developer experience. No need to uncomment a whole input argument, but the parent and target child arg would suffice.
Modifications:
Add defaults to the child values in a map input argument.

[Terraform Azure] feat: add granular defaults

---

terraform/aws/control-plane/main.tf
terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/variables.tf
terraform/aws/location/variables.tf
terraform/aws/private-package/variables.tf
terraform/examples/AWS-private-location/README.md
terraform/examples/AWS-private-location/main.tf
terraform/examples/AWS-private-package/README.md
terraform/examples/AWS-private-package/main.tf
terraform/examples/AZURE-private-location/README.md
terraform/examples/AZURE-private-location/main.tf

Motivation:
Add granular defaults to input arg objects in order to improve the developer experience. No need to uncomment a whole input argument, but the parent and target child arg would suffice.
Modifications:
Add defaults to the child values in a map input argument.

[Terraform AWS] feat: add granular defaults for input args

---

terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/modules/ecs/variables.tf
terraform/aws/control-plane/variables.tf
terraform/examples/AWS-private-location/README.md
terraform/examples/AWS-private-location/main.tf
terraform/examples/AWS-private-package/README.md
terraform/examples/AWS-private-package/main.tf

Motivation:
Enterprises requiring private images will need to configure a custom init container image.
Modification:
Add `task.init.image` to the control plane module, with a default value of `busybox`.

[TF-AWS] Feat: custom init container image support

---

terraform/aws/control-plane/main.tf
terraform/aws/control-plane/modules/ecs/main.tf
terraform/aws/control-plane/modules/ecs/variables.tf
terraform/aws/control-plane/modules/iam/main.tf
terraform/aws/control-plane/modules/iam/variables.tf
terraform/aws/control-plane/variables.tf
terraform/examples/AWS-private-package/README.md
terraform/examples/AWS-private-package/main.tf

Motivation:
Enable building from source by allowing end users to integrate their Git credentials or SSH key.
Modifications:
- Update the init container in the ECS module to inject the required SSH key or Git credentials.
- Mount the necessary volumes to the appropriate paths for both the init container and the control plane container within the ECS module.
- Add the required IAM permissions to read Git secrets (password/token and SSH private key) from AWS Secrets Manager (ASM).

[TF-AWS] Build from sources support

---

terraform/aws/control-plane/main.tf
terraform/aws/control-plane/modules/iam/main.tf
terraform/aws/control-plane/modules/iam/variables.tf

[fix: allow get secret value of task secrets, closes misc-510](https://github.com/gatling/gatling-enterprise-control-plane-deployment/commit/e7f805a9479d0e42a0b02ae84f1d7dfdab3ed253)
**Motivation:**
Task fail to deploy because configured secrets are not readable.
**Modification:**
Add all secrets ARN from task to IAM role allowing to get secret value.
---
`terraform plan` with `task.secrets = [{ "valueFrom": "test"}]`
```
+ resource "aws_iam_policy" "asm_policy" {
+ arn              = (known after apply)
+ attachment_count = (known after apply)
+ id               = (known after apply)
+ name             = "tpetillot-control-plane-asm-policy"
+ name_prefix      = (known after apply)
+ path             = "/"
+ policy           = jsonencode(
{
+ Statement = [
+ {
+ Action   = [
+ …
```

fix: allow get secret value of task secrets, closes misc-510

---

terraform/azure/control-plane/main.tf
terraform/azure/control-plane/modules/container-app/main.tf
terraform/azure/control-plane/modules/container-app/variables.tf
terraform/azure/control-plane/modules/role-assignment/main.tf
terraform/azure/control-plane/modules/role-assignment/variables.tf
terraform/azure/control-plane/modules/storage-account/main.tf
terraform/azure/control-plane/modules/storage-account/outputs.tf
terraform/azure/control-plane/modules/storage-account/variables.tf
terraform/azure/control-plane/variables.tf
terraform/azure/private-package/main.tf
terraform/examples/AZURE-private-location/README.md
terraform/examples/AZURE-private-location/main.tf
terraform/examples/AZURE-private-package/README.md
terraform/examples/AZURE-private-package/main.tf

Motivation:
Enable building from source by allowing end users to integrate their Git credentials or SSH key.
Modifications:
- Add an init container in the container-app module to inject the required SSH key or Git credentials & CP config.
- Mount the necessary volumes to the appropriate paths for both the init container and the control plane container within the container-app module.
- Add conditional custom role permissions to retrieve git credentials/SSH private key from Key Vault/Storage Account.

[TF-Azure] Build from sources support

---

terraform/azure/control-plane/modules/role-assignment/main.tf

Motivation:
Resource group remains after a simulation is completed and the virtual machine(s), IP(s), and disk(s) are not deleted.
Modification:
Add missing Azure permission on the custom role in order to read resourceGroups.
`Microsoft.Resources/subscriptions/resourceGroups/read`

fix: add missing resourceGroups read permission

---

terraform/examples/GCP-private-location/README.md
terraform/examples/GCP-private-location/main.tf
terraform/examples/GCP-private-package/README.md
terraform/examples/GCP-private-package/main.tf
terraform/gcp/location/variables.tf

Motivation:
Create a load generator under a project, but with a shared VPC network/subnetwork from a host project. 
Modifications:
Add an extra optional project field in the network-interface of the GCP location configuration block.

[GCP TF] Feat: add optional project field for location's network interface

---

helm-chart/Chart.yaml
helm-chart/templates/deployment.yaml
helm-chart/templates/rolebinding.yaml
helm-chart/templates/serviceaccount.yaml
helm-chart/values.yaml

Motivation:
Reuse existing `ServiceAccount` with the control plane pod to accommodate certain Kubernetes setups where a single `ServiceAccount` is defined per `namespace`, so all pods running in a `namespace` must share a single predefined `ServiceAccount`.
Modifications:
- Added support to reuse an existing `ServiceAccount` with the control plane pod.
- Improved comments for PL ID and image for better clarity.

[Helm] Feat: Add support to reuse existing ServiceAccount with control plane pod

---

helm-chart/templates/_config.tpl

Motivation:
Location system properties are expected as a map and not a list.
Modifications:
Convert system properties to a map in _config.tpl

fix: convert system-properties list to map

---

helm-chart/templates/_config.tpl

Motivation:
Enforce location system property keys as strings.

[Helm] Fix: Enforce quotes on system properties keys

---

terraform/examples/GCP-private-package/main.tf
terraform/gcp/control-plane/modules/iam/main.tf
terraform/gcp/location/variables.tf

Motivation:
Users configuring `location.instance-template` expect the `location.machine` block to be entirely ignored. However, due to the default values assigned to `location.machine,` the configuration remains non-null even when omitted by the user. This leads to validation logic incorrectly detecting both instance-template and machine as present, triggering an error:
> either instance-template or machine configuration must be present
Modifications:
- Allowing `location.machine` to be null
- Preventing validation from running if `location.machine` is not defined

Fix: assign location.machine default to null

---

helm-chart/templates/deployment.yaml
helm-chart/values.yaml

**Motivation:**
Adding container-level security context provides finer-grained control over permissions and runtime behavior beyond what the pod level security context can enforce. While the pod security context applies defaults to all containers, some workloads require specific overrides (e.g., restricting capabilities, defining read-only root filesystems, or dropping privileges for individual containers).
**Modifications:**
- Add `containerSecurityContext` on `values.yaml`.
- Add `securityContext` under containers in `deployment.yaml`

Feat: add container security context
